networks:
  graphql-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

services:
  graphql-redis:
    image: redis:7
    container_name: graphql-redis
    networks:
      - graphql-network

  graphql-db:
    image: postgres:15
    container_name: graphql-db
    restart: always
    environment:
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: secret-password-xjectro:D
      POSTGRES_DB: graphql
    ports:
      - "5432:5432"
    networks:
      - graphql-network

  graphql:
    container_name: graphql
    depends_on:
      - graphql-db
      - graphql-redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - graphql-network
    command: sh -c "
      until pg_isready -h graphql-db -p 5432; do echo 'waiting for postgres...'; sleep 1; done && \
      pnpm db:reset && pnpm db:migrate && pnpm db:generate && \
      pnpm run build && pnpm run start"
